server:
  port: 8088
  
spring: 
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql0819?characterEncoding=UTF-8
    username: root
    password: 520521
