server:
  port: 8088
  
spring: 
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xawn.f3322.net:3306/prj8?characterEncoding=UTF-8
    username: prj8
    password: #@$*()#$
